version: '2'

services:
  db:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongodb_backup:/docker-entrypoint-initdb.d/
      - ./database:/data/db

  server:
    image: ubuntu:xenial
    restart: always
    depends_on:
      - db
    links:
      - db
    working_dir: /usr/local/leanote/bin
    entrypoint:
      - sh
      - run.sh
    ports:
     - "9000:9000"
    volumes:
      - "./:/usr/local/leanote"
